from cctf.cctfTools import generateCctfTrackNetBadmintonImagesNpyFile, generateCctfVideoFileFromVideo

generateCctfVideoFileFromVideo()
generateCctfTrackNetBadmintonImagesNpyFile(224)
generateCctfTrackNetBadmintonImagesNpyFile(112)
